
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int RDECLARE = 34;
  public static final int MENQUE = 20;
  public static final int RSTRING = 36;
  public static final int RTRUE = 18;
  public static final int RWHILE = 43;
  public static final int CONCAT = 17;
  public static final int ENTERO = 29;
  public static final int RVOID = 47;
  public static final int llaveder = 13;
  public static final int RFALSE = 19;
  public static final int RELSE = 42;
  public static final int IDENTIFICADOR = 39;
  public static final int RPRINT = 33;
  public static final int IGUAL = 38;
  public static final int parder = 7;
  public static final int IGUALQUE = 25;
  public static final int CORDER = 16;
  public static final int MAYIGUALQUE = 23;
  public static final int UMENOS = 32;
  public static final int menos = 3;
  public static final int RDO = 44;
  public static final int EOF = 0;
  public static final int PARIZQ = 10;
  public static final int DECIMAL = 30;
  public static final int mas = 2;
  public static final int MENIGUALQUE = 22;
  public static final int RELSEIF = 41;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int CADENA = 31;
  public static final int entero = 52;
  public static final int por = 4;
  public static final int dospuntos = 14;
  public static final int MAYQUE = 21;
  public static final int RRETURN = 48;
  public static final int RNUMBER = 35;
  public static final int llaveizq = 12;
  public static final int PTCOMA = 9;
  public static final int ROR = 27;
  public static final int RBOOLEAN = 37;
  public static final int parizq = 6;
  public static final int RFOR = 45;
  public static final int div = 5;
  public static final int PARDER = 11;
  public static final int pr_case = 51;
  public static final int CORIZQ = 15;
  public static final int RBREAK = 49;
  public static final int pr_switch = 50;
  public static final int RIF = 40;
  public static final int RFUNCTION = 46;
  public static final int RNOT = 26;
  public static final int RAND = 28;
  public static final int DIFQUE = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "parizq",
  "parder",
  "COMA",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "llaveizq",
  "llaveder",
  "dospuntos",
  "CORIZQ",
  "CORDER",
  "CONCAT",
  "RTRUE",
  "RFALSE",
  "MENQUE",
  "MAYQUE",
  "MENIGUALQUE",
  "MAYIGUALQUE",
  "DIFQUE",
  "IGUALQUE",
  "RNOT",
  "ROR",
  "RAND",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RPRINT",
  "RDECLARE",
  "RNUMBER",
  "RSTRING",
  "RBOOLEAN",
  "IGUAL",
  "IDENTIFICADOR",
  "RIF",
  "RELSEIF",
  "RELSE",
  "RWHILE",
  "RDO",
  "RFOR",
  "RFUNCTION",
  "RVOID",
  "RRETURN",
  "RBREAK",
  "pr_switch",
  "pr_case",
  "entero"
  };
}

